config/routes.rb
# typed: strict
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # == Redirects
  constraints subdomain: "www" do
    get "(*any)" => redirect(subdomain: "", status: 302)
  end

  # == Healthcheck
  Healthcheck.routes(self)

  # == Good Job
  if Rails.env.development?
    mount GoodJob::Engine => "/good_job"
    # else
    #   authenticate :user, ->(user) {
    #     user = T.let(user, User)
    #     user.admin?
    #   } do
    #     mount GoodJob::Engine => "/good_job"
    #   end
  end

  # == Devise
  devise_for :users, only: []
  # devise_for :users,
  #            skip: %i[sessions confirmations passwords],
  #            controllers: {
  #              omniauth_callbacks: "users/omniauth_callbacks",
  #              registrations: "users/registrations",
  #            },
  #            path: "/user",
  #            path_names: {
  #              sign_up: "register",
  #              edit: "settings",
  #            }
  # devise_scope :user do
  #   resource :sessions,
  #            path: "/",
  #            module: "users",
  #            as: :user_session,
  #            only: [] do
  #              get :login, action: :new, as: :new
  #              post :login, action: :create, as: ""
  #              post :logout, action: :destroy, as: :destroy
  #            end
  #   scope :user, module: "users", as: :user do
  #     resource :confirmation,
  #              only: %i[new show],
  #              path: "/verification",
  #              path_names: {
  #                new: "resend",
  #              }
  #     resource :password,
  #              only: %i[new edit update],
  #              path_names: {
  #                new: "reset",
  #                edit: "change",
  #              }
  #   end
  # end

  # == GraphQL
  scope :graphql, controller: :graphql do
    get "/", action: :graphiql, as: :graphiql
    post "/", action: :execute, as: :graphql
  end

  # == Apply
  get "/apply" => redirect("https://tally.so/r/w2NWzj")

  # == Errors
  scope controller: :errors do
    match "/401", action: :unauthorized, via: :all
    match "/404", action: :not_found, via: :all
    match "/422", action: :unprocessable_entity, via: :all
    match "/500", action: :internal_server_error, via: :all
  end

  # == Pages
  root "home#show"
  get "/src" => redirect(
    "https://github.com/hulloitskai/launchweek",
    status: 302,
  )
  get "/ideas" => redirect(
    "https://www.figma.com/community/file/1298426462618518881/launchweek-idea-slide",
    status: 302,
  )
  get "/sesh1" => redirect(
    "https://tally.so/r/wo2VGP",
    status: 302,
  )
  get "/sesh2" => redirect(
    "https://tally.so/r/wLPvr2",
    status: 302,
  )

  # == Development
  if Rails.env.development?
    get "/test" => "test#show"
    get "/mailcatcher" => redirect("//localhost:1080", status: 302)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" data-mantine-color-scheme="light">
  <head>
    <%# == Favicon %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <%# == Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

    <%# == Viewport %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%# == Content Security Policy & CSRF %>
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>

    <%# == Action Cable %>
    <%= action_cable_meta_tag %>

    <%# == Active Storage %>
    <meta name="active-storage-direct-uploads-url" content="<%= rails_direct_uploads_path %>">

    <%# == Environment %>
    <meta name="env" content="<%= Rails.env %>">

    <%# == GraphQL %>
    <meta name="graphql-url" content="<%= graphql_path %>">

    <%# == Sentry %>
    <% scoped do %>
      <% config = Sentry.configuration %>
      <% if (dsn = config.dsn.presence) %>
        <meta name="sentry-dsn" content="<%= dsn %>">
        <meta name="sentry-traces-sample-rate" content="<%= config.traces_sample_rate %>">
        <% if (user = current_user) %>
          <meta name="sentry-user" content="<%= user.sentry_info.to_json %>">
        <% end %>
      <% end %>
    <% end %>

    <%# == FullStory %>
    <% if (org_id = ENV["FULLSTORY_ORG_ID"].presence) %>
      <meta name="fullstory-org-id" content="<%= org_id %>">
      <% if (user = current_user) %>
        <meta name="fullstory-identity" content="<%= user.fullstory_identity.to_json %>">
      <% end %>
    <% end %>

    <%# == Vite %>
    <%= vite_client_tag %>
    <%= vite_typescript_tag "sentry" %>
    <%= vite_typescript_tag "fullstory" %>
    <% if local_assigns.include?(:page) %>
      <%= vite_react_refresh_tag %>
      <%= vite_typescript_tag "application", media: nil %>
    <% end %>

    <%# == Google Analytics %>
    <% if (measurement_id = ENV["GOOGLE_ANALYTICS_MEASUREMENT_ID"].presence) %>
      <script src="https://www.googletagmanager.com/gtag/js?id=<%= measurement_id %>" async></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){ dataLayer.push(arguments); }
        gtag("js", new Date());
        gtag("config", "<%= measurement_id %>");
      </script>
    <% end %>

    <% # == Mapbox %>
    <% if (token = ENV["MAPBOX_ACCESS_TOKEN"].presence) %>
      <meta name="mapbox-access-token" content="<%= token %>">
    <% end %>

    <%# == Inertia %>
    <%== inertia_headers %>
    <%== inertia_assets type: :page, media: nil %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>